### ISSUE TITLE
It Doesn't Work(1.12.2)

### ISSUE THREAD

**Issue by KenyMylankca** [blay09/PrettyBeaches#10]
It doesn't work in [my modpack.](https://github.com/KenyMylankca/Kenijeys-Modpack) I'm using Climatic Biomes and Biomes OP that effects the terrain as i know, and don't know why PB doesn't work. I tried many biomes, broke sand, dirt, gravel, etc... But it didn't work. Can you try it in my modpack please? Thanks.

**Comment by blay09** [comment]
Did you try it in Survival Mode?

**Comment by KenyMylankca** [comment]
yeah, didn't work as well.

**Comment by KenyMylankca** [comment]
oh wait i tried with sand and it worked. i think i need to add such blocks from all other mods (bop, underground biomes, etc...) to the config, one by one... thanks anyway!

**Comment by KenyMylankca** [comment]
xD yeah this is what i did so far: https://github.com/KenyMylankca/Kenijeys-Modpack/commit/b22157984fcbf51c214f1fd7d06c02019767f129
