### ISSUE TITLE
Not working properly when using FTB Ultimine

### ISSUE THREAD

**Issue by smallerYeet** [blay09/PrettyBeaches#22]
Minecraft : 1.16.3
Forge: 34.1.42
Mod Version: Latest

Very short issue. 
When using [FTB Ultimine](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine), there is a chance for the Water to be in a bugged state. There is water, but it's invisible.
If you want to recreate, just use shapeless until you get this bug.

Other than that the mod works fine!!!

**Comment by BlayTheNinth** [comment]
Does this still happen in more recent Minecraft versions?
